// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joudbvrmpwztuwdygrhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvdWRidnJtcHd6dHV3ZHlncmh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzYzNzQsImV4cCI6MjA2MjU1MjM3NH0.7wF8Ib1jxY5_ILHINPv6L22az2p24e03GLItEGvY8Eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);